# Netlify configuration file

[build]
command = "npm ci --include=dev && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "22.18"
NPM_FLAGS = "--include=dev"

# Development environment
[context.dev.environment]
NODE_ENV = "development"

# Production environment
[context.production.environment]
NODE_ENV = "production"

# Proxy configuration for API calls
# These redirects allow the frontend to call external APIs without CORS issues

# QuickBooks API proxy
[[redirects]]
from = "/api/quickbooks/*"
to = ":VITE_QBO_API_BASE_URL/:splat"
status = 200
force = true
headers = { X-From = "Netlify" }
conditions = { env = ["VITE_QBO_API_BASE_URL"] }

# Perplexity API proxy
[[redirects]]
from = "/api/perplexity/*"
to = "https://api.perplexity.ai/:splat"
status = 200
force = true
headers = { X-From = "Netlify" }

# PDF Service API proxy (if configured)
[[redirects]]
from = "/api/pdf/*"
to = ":VITE_PDF_SERVICE_URL/:splat"
status = 200
force = true
headers = { X-From = "Netlify" }
conditions = { env = ["VITE_PDF_SERVICE_URL"] }

# SPA redirect for React Router
# This must come last to catch all routes not matched above
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers for security
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache control for static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
